CREATE DATABASE IF NOT EXISTS CONCESSIONARIA;
USE CONCESSIONARIA;

CREATE TABLE IF NOT EXISTS CARRO(
	PLACA CHAR(7) PRIMARY KEY,
    MODELO VARCHAR(20) NOT NULL,
    MARCA VARCHAR(15) NOT NULL,
    COR VARCHAR(10) NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    SITUACAO BINARY DEFAULT 1,
    AR_CONDICIONADO BINARY NOT NULL,
    AR_QUENTE BINARY NOT NULL,
    DIRECAO CHAR(1) NOT NULL,
    VIDROS_ELETRICOS BINARY NOT NULL,
    TRAVAS_ELETRICAS BINARY NOT NULL);

CREATE TABLE IF NOT EXISTS VENDAS(
    ID_VENDA INT4 PRIMARY KEY AUTO_INCREMENT,
    PLACA CHAR(7),
    DATA_VENDA DATE) NOT NULL,
    FOREIGN KEY(PLACA) REFERENCES CARRO(PLACA);
